# fly.toml app configuration file generated for ltirun on 2023-05-28T22:22:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ltirun"
primary_region = "otp"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0